<a href="https://colab.research.google.com/github/Qureshiii/Qureshiii/blob/main/Tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [143]:
import torch
print(torch.__version__)

2.11.0+cu128


In [144]:
if torch.cuda.is_available():
  print('GPU is available!')
  print(f'Using GPU :{torch.cuda.get_device_name(0)}')
else:
  print('GPU is not available. Using CPU')

GPU is available!
Using GPU :Tesla T4


### Creating a Tensor

In [145]:
#using empty
a = torch.empty(2,3)

In [146]:
#check type
type(a)

torch.Tensor

In [147]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [148]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [149]:
#using rand
torch.rand(2,3)

tensor([[0.1219, 0.3516, 0.2316],
        [0.2847, 0.3520, 0.2828]])

In [150]:
#use of seed
#manual_seed

torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [151]:
 # Using tensors
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [152]:
# other ways

# using arange
print('using arange -->>',torch.arange(0,10,2))
# using linspace
print('using linspace -->>',torch.linspace(0,10,10))
# using eye
print('using eye -->>',torch.eye(5))
# using full
print('using full -->>',torch.full((3,3),5))

using arange -->> tensor([0, 2, 4, 6, 8])
using linspace -->> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -->> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -->> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### Tensors Shapes

In [153]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [154]:
torch.empty_like(x)

tensor([[      200863218,       200745168,               0],
        [             65, 136151866231584,       386554480]])

In [155]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [156]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [157]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

### Tensor Data types

In [158]:
x.dtype

torch.int64

In [159]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [160]:
torch.tensor([1,2,3,4],dtype=float)

tensor([1., 2., 3., 4.], dtype=torch.float64)

In [161]:
x.to(torch.float)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Mathematical Operations

- 1. Scalar Operations

In [162]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [163]:
# addition
print('# addition',x + 2)

# Subtraction
print('# Subtraction',x - 2)

# Multiplications
print('# Multiplications',x * 3)

# Division
print('# Division',x / 3)

# Integer Division
print('# Integer Division',x * 100 // 3)

# mod
print('# Mod',(x * 100 // 3)%2)

# power
print('# power',x ** 2)

# addition tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])
# Subtraction tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])
# Multiplications tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])
# Division tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])
# Integer Division tensor([[23., 26.],
        [13., 30.]])
# Mod tensor([[1., 0.],
        [1., 0.]])
# power tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])


- 2. Element wise operations

In [164]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [165]:
# add
print('Addition',a+b)
# multiply
print('Multiplication',a*b)
# subtract
print('Subtraction',a-b)
# divide
print('Division',a/b)
# power
print('Power',a**b)
# mod
print('Mod',a%b)

Addition tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])
Multiplication tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])
Subtraction tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])
Division tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])
Power tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])
Mod tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])


In [166]:
c = torch.tensor([1,-2,3,-4])

In [167]:
# absolute
torch.abs(c)

tensor([1, 2, 3, 4])

In [168]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [169]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [170]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [171]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [172]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [173]:
torch.clamp(d,min=2,max=4)

tensor([2.0000, 2.3000, 3.7000, 4.0000])

- 3. Reduction operations

In [174]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [175]:
torch.sum(e)

tensor(24.)

In [176]:
torch.sum(e,dim=0)

tensor([ 8.,  0., 16.])

In [177]:
torch.sum(e,dim=1)

tensor([15.,  9.])

In [178]:
torch.mean(e)

tensor(4.)

In [179]:
torch.mean(e,dim=0)

tensor([4., 0., 8.])

In [180]:
torch.mean(e,dim=1)

tensor([5., 3.])

In [181]:
torch.median(e)

tensor(0.)

In [182]:
torch.min(e)

tensor(0.)

In [183]:
torch.max(e)

tensor(9.)

In [184]:
torch.prod(e)

tensor(0.)

In [185]:
torch.std(e)

tensor(4.4272)

In [186]:
torch.var(e)

tensor(19.6000)

In [187]:
torch.argmax(e)

tensor(5)

In [188]:
torch.argmin(e)

tensor(1)

- 4. Matrix operations

In [189]:
f = torch.randint(size=(2,3),low=0,high=10)
g = torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [190]:
# matrix Multiplication
torch.matmul(f,g)

tensor([[ 87, 119],
        [ 65,  99]])

In [191]:
# dot product
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

torch.dot(vector1,vector2)

tensor(11)

In [192]:
torch.transpose(f,0,1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [193]:
h = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)

In [194]:
torch.det(h)

tensor(-110.)

In [195]:
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

- 5. Comparison Operations

In [196]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [197]:
i > j

tensor([[ True,  True, False],
        [ True, False, False]])

In [198]:
i < j

tensor([[False, False,  True],
        [False,  True,  True]])

In [199]:
i == j

tensor([[False, False, False],
        [False, False, False]])

In [200]:
i != j

tensor([[True, True, True],
        [True, True, True]])

In [201]:
i >= j

tensor([[ True,  True, False],
        [ True, False, False]])

In [202]:
i <= j

tensor([[False, False,  True],
        [False,  True,  True]])

- 6. Special Functions

In [203]:
k = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
k

tensor([[3., 3., 5.],
        [0., 6., 4.],
        [0., 8., 4.]])

In [204]:
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863],
        [  -inf, 2.0794, 1.3863]])

In [205]:
torch.exp(k)

tensor([[2.0086e+01, 2.0086e+01, 1.4841e+02],
        [1.0000e+00, 4.0343e+02, 5.4598e+01],
        [1.0000e+00, 2.9810e+03, 5.4598e+01]])

In [206]:
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000],
        [0.0000, 2.8284, 2.0000]])

In [207]:
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820],
        [0.5000, 0.9997, 0.9820]])

In [208]:
torch.softmax(k,dim=0)

tensor([[0.9094, 0.0059, 0.5761],
        [0.0453, 0.1185, 0.2119],
        [0.0453, 0.8756, 0.2119]])

In [209]:
torch.relu(k)

tensor([[3., 3., 5.],
        [0., 6., 4.],
        [0., 8., 4.]])

- Inplace Operations

In [210]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.9798, 0.5548, 0.6868],
        [0.4920, 0.0748, 0.9605]])
tensor([[0.3271, 0.0103, 0.9516],
        [0.2855, 0.2324, 0.9141]])


In [211]:
m.add_(n)

tensor([[1.3069, 0.5650, 1.6384],
        [0.7776, 0.3072, 1.8746]])

In [212]:
n.add_(m)

tensor([[1.6339, 0.5753, 2.5900],
        [1.0631, 0.5396, 2.7887]])

In [213]:
m

tensor([[1.3069, 0.5650, 1.6384],
        [0.7776, 0.3072, 1.8746]])

In [214]:
n

tensor([[1.6339, 0.5753, 2.5900],
        [1.0631, 0.5396, 2.7887]])

### Copying a Tensor

In [215]:
a = torch.rand(2,3)
a

tensor([[0.7668, 0.1659, 0.4393],
        [0.2243, 0.8935, 0.0497]])

In [216]:
b = a

In [217]:
b

tensor([[0.7668, 0.1659, 0.4393],
        [0.2243, 0.8935, 0.0497]])

In [218]:
b = a.clone()

In [219]:
a

tensor([[0.7668, 0.1659, 0.4393],
        [0.2243, 0.8935, 0.0497]])

In [220]:
b

tensor([[0.7668, 0.1659, 0.4393],
        [0.2243, 0.8935, 0.0497]])

In [221]:
a[0][0]=10

In [222]:
a

tensor([[10.0000,  0.1659,  0.4393],
        [ 0.2243,  0.8935,  0.0497]])

In [223]:
b

tensor([[0.7668, 0.1659, 0.4393],
        [0.2243, 0.8935, 0.0497]])

### Tensor operations on GPU

In [224]:
torch.cuda.is_available()

True

In [225]:
device = torch.device('cuda')

In [226]:
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [227]:
b = a.to(device)

In [228]:
b

tensor([[10.0000,  0.1659,  0.4393],
        [ 0.2243,  0.8935,  0.0497]], device='cuda:0')

### Difference between CPU and GPU

In [233]:
import time

size = 10000

matrix_cpu1 = torch.rand(size,size)
matrix_cpu2 = torch.rand(size,size)

# measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1,matrix_cpu2) # Matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f'Time on CPU : {cpu_time:.4f} Seconds')

# Move matrices to GPU

matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1,matrix_gpu2) # Matrix multiplication on GPU
torch.cuda.synchronize()
gpu_time = time.time() - start_time

print(f'Time on GPU : {gpu_time:.4f} Seconds')

# compare results

print('\nSpeedup (CPU time / GPU time):', cpu_time / gpu_time)

Time on CPU : 15.3698 Seconds
Time on GPU : 0.5880 Seconds

Speedup (CPU time / GPU time): 26.13815827352131


In [236]:
# image Size
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])